### ISSUE TITLE
Multimonitor setups

### ISSUE THREAD

**Issue by laserswald** [wmutils/core#21]
Here we go. I'm working on the multimonitor utilities, and I now have enough info where I can create programs that fulfill my scripts' functions. Before I go any further, I'd like some feedback on the best, most unixy command line interfaces for multimonitor. 

**Which interface do we like the most? Xinerama, or RandR?**
Xinerama indexes each output by a single integer, while RandR references each output by a string with the protocol name followed by a number, i.e. "VGA-0". Xinerama's method of choosing the output is stupid easy, while RandR gives more information to the user. I have a slight lean to Xinerama.

**Which "One Thing (tm)" should each program do in order to maximize usefulness and composibility?** 
The scripts I made only did two things; one listed the outputs RandR style, and the other, when given a screen, gave the output's dimensions. Should I just make those two? Can anyone think of features that one would also need for manipulating multimonitor applications?

**Should I add multimonitor capabilities to wattr?**
I think that finding out which output(s) a window is currently in would be very useful. Adding an extra character option to wattr could be possible, but it starts entangling dependencies a little bit. 

I've already got some of the functionality done, I just need some ideas and guidance on what you guys want me to do.

**Comment by dcat** [comment]
Only thing I know for sure is that I hate `Xinerama` with a burning passion.

I don't run a multi monitor setup, so can you summarise why we would want/need this?

**Comment by laserswald** [comment]
z3bra and I discussed this over IRC, and I am going to move these tools
to opt instead. Sorry, I just haven't gotten to it.
