### ISSUE TITLE
chwb: Include -i flag to report back window's border settings

### ISSUE THREAD

**Issue by Wildefyr** [wmutils/core#25]
There are cases I've found now that being able to get this information back would be handy. I.e. if a window border has been set to nothing and don't want focus.sh to set the border width back to my predefined value when I leave then window. (Currently getting around this issue by having yet another focus script)

Other examples could have a script checking each second for a window border colour change, (i.e. sent by shell script or other process running in window), then do stuff based upon that, I.e. jump to window immediately and set the window border to another colour.

**Comment by dcat** [comment]
`wattr b` already does this
