### ISSUE TITLE
git describe --long --tags gives wrong value

### ISSUE THREAD

**Issue by oberon2007** [wmutils/core#29]
Something does not look right here. For some reason release v1.2 is not shown:
```
$ git describe --long --tags
v1.1-0-g7b86e8b
```

**Comment by oberon2007** [comment]
git describe seems to be printing the commits of branch **wmlib**

**Comment by z3bratabs** [comment]
Bernhard Landauer wrote:
> Something does not look right here For some reason release v12 is not shown:
> ```
> $ git describe --long --tags
> v11-0-g7b86e8b
> ```
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/wmutils/core/issues/29

We rolled back to when wmutils had no dependencies other than libxcb.
So version 1.2, which was tagged after exporting everything to libwm
simply doesn't exist anymore.

**Comment by oberon2007** [comment]
Thank you for the explanation.
