### ISSUE TITLE
pfw always prints 0x00000001

### ISSUE THREAD

**Issue by CrackedP0t** [wmutils/core#32]
No matter what I do, or which window I focus, pfw prints 0x00000001.

Using Arch Linux and no WM or DE, only wmutils.

**Comment by Wildefyr** [comment]
Just to confirm, you are using `wtf` to focus a window for example using `wtf $(lsw)` when there is one window on the screen.

**Comment by CrackedP0t** [comment]
No, I was just hovering over it. Never mind, thank you!

**Comment by Wildefyr** [comment]
Ah, a PEBKAC! No worries.
