### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by Anachron** [wmutils/core#56]
Please make a new release so it can be packaged accordingly.

**Comment by AladW** [comment]
I do not see open issues here, is there something else holding back a new release?

Note: should there be a new release, it would also be nice to have it verified by a gpg signature. See:

https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by z3bra** [comment]
There you go, two new tags.
Signed releases are not planned, though.
