### ISSUE TITLE
Documentation wrt. IRC channel

### ISSUE THREAD

**Issue by dami0** [wmutils/core#58]
The IRC channel is given quite clearly, but not the network it's on, unless I missed it somewhere further up.

**Comment by z3bra** [comment]
That is correct, thanks for reporting. The channel is not frequented anymore, so I removed it from the README.

**Comment by dami0** [comment]
Bummer. I wanted to actually use this for enterprise purposes. Long story...

**Comment by z3bra** [comment]
Entreprise purpose? What do you mean?

**Comment by dami0** [comment]
As in, I wanted to try and use it at work to automate some things.
