### ISSUE TITLE
util.c fatal error.

### ISSUE THREAD

**Issue by b0nete** [wmutils/core#59]
Hi, I'm having the following error at the moment of executing 'make command'

Clarified that i'm installed the dependencies xdotools and wmutils.

The error is a follow:

> └──╼ #make
> CC util.c
> util.c:5:10: fatal error: xcb/xcb_aux.h: No such file or directory
>  #include <xcb/xcb_aux.h>
>           ^~~~~~~~~~~~~~~
> compilation terminated.
> Makefile:37: recipe for target 'util.o' failed
> make: *** [util.o] Error 1

Thanks for your help.

**Comment by dcat** [comment]
you’re missing a dependency.

since you didn’t include which distro you’re running, i don’t know the exact package name. 

most likely it’s something like `libxcb-util`, maybe a `-dev` suffix on it.

**Comment by coolcatmick** [comment]
I'm getting this same error

**Comment by z3bra** [comment]
If it's the same error, then it's the same solution. Please check the answer given above.

**Comment by coolcatmick** [comment]
I appreciate it, it was libx11 devel that I thought had been installed already
