### ISSUE TITLE
DWM support

### ISSUE THREAD

**Issue by paperbenni** [wmutils/core#61]
I'm on dwm and a lot of stuff doesnt work. Selecting and listing windows works fine, but focusing and moving them with wmutils doesnt do anything. No error messages, just nothing. It would be really awesome if this project would support dwm at some point.

**Comment by dcat** [comment]
that’s not how it works. 

if anything, `dwm` would have to start supporting wmutils, though i don’t see why they would.

**Comment by z3bra** [comment]
`dwm` (just like any other WM) will ask the X server to redirect all
configure requests onto it. So when you call `wmv` or `chwb` (or whatever
wmutils tool), you're effectively asking dwm to do it for you.

I took a brief look at `dwm.c`, and it will only honor configure requests
for windows that are in floating mode.
In "normal" mode, these requests are simply ignored.

If you want wmutils to handle windows for you, then don't run a WM,
or run one that will transparently forward ALL configure requests to
the X server. Such WM include cwm[0], swm[1] or glazier[2].

[0]: http://cvsweb.openbsd.org/cgi-bin/cvsweb/xenocara/app/cwm/
[1]: https://github.com/dcat/swm
[2]: http://git.z3bra.org/glazier
