### ISSUE TITLE
cannot find -lxcb-cursor

### ISSUE THREAD

**Issue by chrisJuresh** [wmutils/core#64]
When running make (and sudo make) I get the following error
```
LD pfw
/usr/bin/ld: cannot find -lxcb-cursor
collect2: error: ld returned 1 exit status
make: *** [Makefile:36: pfw] Error 1
```
libxcb is installed and I'm on artix using dwm

**Comment by turquoise-hexagon** [comment]
`xcb-util-cursor` is probably the dependency you're looking for

**Comment by lwilletts** [comment]
Yes, it is now required to build `slw`
