### ISSUE TITLE
error trying to install wmutils

### ISSUE THREAD

**Issue by gitlerat** [wmutils/core#65]
Hi, I am using debian buster. Downloaded the repo via git clone and then hit "make install" in the core directory.
I got this error:
```
CC util.c
util.c:5:10: fatal error: xcb/xcb_aux.h: No such file or directory
 #include <xcb/xcb_aux.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:40: util.o] Error 1

```
I have zero knowledge about C coding - I hope somebody can help me out :)

**Comment by z3bra** [comment]
You are missing a library, libxcb-aux. I don't know the exact package name on debian, so you gotta search by yourself. It should be something like libxcb-aux-dev. You 
Will probably need a few more after that (libxcb-cursor for example).

**Comment by gitlerat** [comment]
Hi z3bra, I have to excuse me! The solution was already in the closed issues - my fault! Thank you still for your answer! Your answer was the solution too!
