### ISSUE TITLE
wmv has no effect

### ISSUE THREAD

**Issue by sonofevil** [wmutils/core#70]
I run something like `wmv 17 33 0x010196c6` and nothing happens. The window does not move.

I double checked that the window ID is correct.

Passive tools like wattr work fine with the same ID.

Operating System: EndeavourOS 
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.105.0
Qt Version: 5.15.9
Kernel Version: 6.1.30-1-lts (64-bit)
Graphics Platform: X11

**Comment by z3bra** [comment]
wmutils doesn't work well with reparenting  WM like the one used in KDE plasma. Try tu use `pdw` instead of `pfw` to get the ID of the decoration window rather than the reparented window.

Le 27 mai 2023 05:14:57 GMT-07:00, sonofevil ***@***.***> a écrit :

**Comment by sonofevil** [comment]
Well, I was using lsw, and pdw gives me the same ID. The pfw ID actually works with wmv.

It's my fault. I was using "lsw" instead of "lsw -a". The geometries shown by wattr looked right, so I didn't realize I had the wrong IDs. My understanding of how parent and child windows work is somewhat limited. I guess I was trying to move unmovable child windows.

**Comment by sonofevil** [comment]
Now I have a follow-up issue though. The IDs I get for "normal" windows (Firefox, Kate, Dolphin etc, like, the ones I can move around with a mouse) with "pfw" actually do not appear in "lsw -a". Why could that be?

**Comment by sonofevil** [comment]
Okay, I guess I should use "wmctrl -l" instead of wmutils to get window IDs.

**Comment by dcat** [comment]
what a great example of tool misuse. 


you are trying to open a can of sardines with a hairdryer.

**Comment by sonofevil** [comment]
thanks for the help

**Comment by z3bra** [comment]
`pfw` gives the ID of the window that has keyboard focus. In your case, this window is the child of a decoration window created by your DE. When you run `lsw` it only lists the IDs of the direct children of the root window.
To list the children of a specific window, use `lsw $WID`.

Le 28 mai 2023 03:41:14 GMT-07:00, sonofevil ***@***.***> a écrit :
